# use kramdown (GitHub Pages default) in GFM mode
markdown: kramdown
kramdown:
  input: GFM

  # choose your math engine: mathjax is easiest on GitHub Pages
  math_engine: mathjax

  # tell it what delimiters to look for
  math_engine_opts:
    tex2jax:
      inlineMath: [["$", "$"], ['\\(', '\\)']]
      displayMath: [["$$", "$$"], ['\\[', '\\]']]
